import type { Codemap, Trace } from '@infinity-canvas/schema';
import { parseCodemap, safeParseCodemap } from '@infinity-canvas/schema';
import type { LLMProvider } from './llmProviders';
import type { ContextPack } from './contextPacker';

// ── Types ──────────────────────────────────────────────

export interface EnrichInput {
  structural: Codemap;
  pack?: ContextPack;
  llm: LLMProvider;
  allowedPaths: string[];
}

export interface EnrichResult {
  codemap: Codemap;
  diagnostics: {
    strippedLocations: number;
    repaired: boolean;
    provider: string;
  };
}

// ── Prompt ─────────────────────────────────────────────

const SYSTEM_ENRICH = `You are a code architecture expert. Refine a structural codemap by adding trace guides, better titles, and architectural insight.

Output ONLY valid JSON — no markdown fences. Keep the same schemaVersion and id from input.

Schema location fields: id, path, lineNumber, lineContent?, title?, description?
Trace fields: id, title, description, locations[], traceTextDiagram?, traceGuide?

IMPORTANT: You may ONLY use locations with paths from this ALLOWED list:
{allowedPaths}

Keep existing trace ids (1,2,3). Add traceGuide with detailed analysis in Markdown.`;

function buildEnrichPrompt(structural: Codemap, pack: ContextPack | undefined, allowedPaths: string[]): { system: string; user: string } {
  const pathsSection = allowedPaths.map(p => `  - ${p}`).join('\n');
  const system = SYSTEM_ENRICH.replace('{allowedPaths}', pathsSection);

  const userParts: string[] = [];
  userParts.push(`Structural codemap to enrich:\n\`\`\`json\n${JSON.stringify({ traces: structural.traces, title: structural.title }, null, 2)}\n\`\`\``);

  if (pack) {
    userParts.push(`Project tree:\n${pack.tree}`);
    for (const m of pack.manifests) {
      userParts.push(`File: ${m.path}\n\`\`\`\n${m.content.slice(0, 1000)}\n\`\`\``);
    }
  }

  userParts.push('\nEnrich the codemap: add traceGuide to each trace, refine descriptions, keep only allowed paths.');
  return { system, user: userParts.join('\n\n') };
}

// ── Post-process ───────────────────────────────────────

function normalizePath(p: string): string {
  return p.replace(/^\.\//, '');
}

function filterLocations(trace: Trace, allowed: Set<string>): { kept: number; stripped: number } {
  const before = trace.locations.length;
  trace.locations = trace.locations.filter(loc => allowed.has(normalizePath(loc.path)));
  return { kept: trace.locations.length, stripped: before - trace.locations.length };
}

function mergeTraces(structural: Trace[], enriched: Trace[]): Trace[] {
  // Prefer enriched traces, but keep structural if enriched trace has no locations
  const result: Trace[] = [];
  const enrichedById = new Map(enriched.map(t => [t.id, t]));

  for (const sTrace of structural) {
    const eTrace = enrichedById.get(sTrace.id);
    if (eTrace && eTrace.locations.length > 0) {
      result.push({ ...sTrace, ...eTrace, locations: eTrace.locations, id: sTrace.id });
    } else {
      result.push(sTrace);
    }
  }

  // Add new traces from enrich that don't exist in structural
  for (const eTrace of enriched) {
    if (!result.some(t => t.id === eTrace.id) && eTrace.locations.length > 0) {
      result.push(eTrace);
    }
  }

  return result;
}

// ── Mock Enrich ────────────────────────────────────────

function mockEnrich(structural: Codemap, allowedPaths: string[]): Codemap {
  const enriched = JSON.parse(JSON.stringify(structural)) as Codemap;
  const allowed = new Set(allowedPaths.map(normalizePath));

  for (const trace of enriched.traces) {
    // Filter locations
    trace.locations = trace.locations.filter(loc => allowed.has(normalizePath(loc.path)));

    // Add mock traceGuide
    if (!trace.traceGuide) {
      const fileList = trace.locations.slice(0, 3).map(l => `- \`${l.path}\``).join('\n');
      trace.traceGuide = `## ${trace.title}\n\n${trace.description}\n\n### Key files\n${fileList}\n\n*Auto-generated by Mock Enrich*`;
    }

    // Refine title
    if (trace.title && !trace.title.includes(':')) {
      trace.title = `${trace.title}: ${trace.locations.length} files`;
    }
  }

  enriched.metadata.generationSource = 'llm-enrich-mock';
  return enriched;
}

// ── Main ───────────────────────────────────────────────

export async function enrichCodemap(input: EnrichInput): Promise<EnrichResult> {
  const { structural, pack, llm, allowedPaths } = input;
  const allowed = new Set(allowedPaths.map(normalizePath));
  let strippedLocations = 0;
  let repaired = false;

  // Mock path — deterministic, no API
  if (llm.name === 'mock') {
    const codemap = mockEnrich(structural, allowedPaths);
    return { codemap, diagnostics: { strippedLocations: 0, repaired: false, provider: 'mock' } };
  }

  // LLM path
  const { system, user } = buildEnrichPrompt(structural, pack, allowedPaths);

  try {
    const raw = await llm.complete([
      { role: 'system', content: system },
      { role: 'user', content: user },
    ]);

    let cleaned = raw.trim();
    cleaned = cleaned.replace(/^```(?:json)?\s*\n?/, '').replace(/\n?\s*```$/, '');
    cleaned = cleaned.trim();

    const result = safeParseCodemap(cleaned);

    if (!result.success) {
      // Fallback to mock on parse failure
      const codemap = mockEnrich(structural, allowedPaths);
      return { codemap, diagnostics: { strippedLocations: 0, repaired: true, provider: llm.name } };
    }

    const enriched = result.data;

    // Filter locations to allowed paths only
    for (const trace of enriched.traces) {
      const { stripped } = filterLocations(trace, allowed);
      strippedLocations += stripped;
    }

    // Merge with structural (keep structural ids, add enrich data)
    const merged = mergeTraces(structural.traces, enriched.traces);

    const codemap: Codemap = {
      ...structural,
      traces: merged,
      metadata: { ...structural.metadata, generationSource: 'llm-enrich' },
    };

    return { codemap, diagnostics: { strippedLocations, repaired: false, provider: llm.name } };
  } catch {
    // Fallback to mock on any error
    const codemap = mockEnrich(structural, allowedPaths);
    return { codemap, diagnostics: { strippedLocations: 0, repaired: true, provider: llm.name } };
  }
}
